[versions]
jetbrains-annotations = "26.0.2-1"
jspecify = "1.0.0"
sqlite-jdbc = "3.45.1.0"
slf4j = "2.0.13"
jda = "5.0.0-beta.21"
snakeyaml = "2.2"
okhttp = "4.11.0"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

[plugins]
